// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDufGttNDdux6jAsqU3rn1PIm37ryrNxaY',
    appId: '1:212947201793:web:b1b11c9a827f78d840b500',
    messagingSenderId: '212947201793',
    projectId: 'authentication-flutter-ff3ae',
    authDomain: 'authentication-flutter-ff3ae.firebaseapp.com',
    storageBucket: 'authentication-flutter-ff3ae.firebasestorage.app',
    measurementId: 'G-KJ3162HQVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7uwSen3-vdcgQPmN6k8e5iEdHhqx_jA',
    appId: '1:212947201793:android:0c68da629ce3b52440b500',
    messagingSenderId: '212947201793',
    projectId: 'authentication-flutter-ff3ae',
    storageBucket: 'authentication-flutter-ff3ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJBiBNx3b3obwoif-Z_HGBoKqav4Z3uw',
    appId: '1:212947201793:ios:653c8e756753b55340b500',
    messagingSenderId: '212947201793',
    projectId: 'authentication-flutter-ff3ae',
    storageBucket: 'authentication-flutter-ff3ae.firebasestorage.app',
    iosBundleId: 'com.example.authenticationFlutter',
  );
}
